sudo: require
dist: xenial
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk texlive-generic-extra


script:
  - make
