sudo: require
dist: xenial
language: bash

before_install:
  - sudo apt -qq update
  - sudo apt install -y texlive-base texlive-latex-base \
  texlive-latex-extra texlive-fonts-recommended \
  texlive-fonts-extra latexmk texlive-generic-extra \
  texlive-bibtex-extra biber texlive-science \
  texlive-math-extra
  - sudo apt -y upgrade

script:
  - make
after_success:
  - bash push_pdf.sh
